project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer:
    center: |
      License: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a> ·
      © 2025 Rodrigo Silva Ferreira
  navbar:
    title: Rodrigo Silva Ferreira
    right:
      - href: talks.qmd
      - href: projects/index.qmd
      - href: blog/index.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/rsf309/
      - icon: github
        href: https://www.github.com/rodrigosf672
      - icon: youtube
        href: https://www.youtube.com/@rodrigosf672
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=FoA5dgMAAAAJ
  favicon: favicon.ico
format:
  html:
    fontsize: 20px
    theme: [cosmo, styles.scss]
